name: Build Package
on:
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          auto-activate-base: true
          activate-environment: ""
      - shell: cmd
        run: conda install conda-build --yes
      - shell: cmd
        run: conda info
      - shell: cmd
        run: conda config --show-sources
      - shell: cmd
        run: conda list --show-channel-urls
      - shell: cmd
        run: conda build recipe --python 3.8
